# Generated by Django 4.2.23 on 2025-08-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_message',
            field=models.TextField(blank=True, help_text='Message from Richard to customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_notified',
            field=models.BooleanField(default=False, help_text='Whether customer has been notified of status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
