# Generated by Django 4.2.16 on 2025-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_admin_message_booking_customer_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_time_notification_sent',
            field=models.BooleanField(default=False, help_text='Whether customer has been notified of date/time changes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_confirmed_date',
            field=models.DateField(blank=True, help_text='Previous confirmed date for change detection', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_confirmed_time',
            field=models.TimeField(blank=True, help_text='Previous confirmed time for change detection', null=True),
        ),
    ]
