// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmsdwpbiqlvxogcleglj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tc2R3cGJpcWx2eG9nY2xlZ2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzY2ODMsImV4cCI6MjA3MDc1MjY4M30.7MwXHu4Fem_lvaEWWtu7rOZobyj84lTTT6Vo6_xQP2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});